wandb_version: 1

latent_size:
  desc: null
  value: 8
update_mlp_shape:
  desc: null
  value:
  - 18
  - 18
  - 18
choice_mlp_shape:
  desc: null
  value:
  - 16
  - 16
  - 16
beta_scale:
  desc: null
  value: 1.0e-05
penalty_scale:
  desc: null
  value: 1.0e-10
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.8
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1728530649
    t:
      1:
      - 12
      - 45
      - 55
      2:
      - 12
      - 45
      - 55
      3:
      - 16
      - 23
      4: 3.9.19
      5: 0.17.8
      8:
      - 5
      13: linux-x86_64
